### ISSUE TITLE
Hyprlang not building :(

### ISSUE THREAD

**Issue by j-koziel** [hyprwm/hyprlang#71]
Not searching for unused variables given on the command line.
-- Configuring hyprlang in Release
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /home/jonathan/Downloads/hyprlang-0.6.1/build
➜  hyprlang-0.6.1 cmake --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`

[ 33%] Building CXX object CMakeFiles/hyprlang.dir/src/common.cpp.o
[ 66%] Building CXX object CMakeFiles/hyprlang.dir/src/config.cpp.o
In file included from /home/jonathan/Downloads/hyprlang-0.6.1/src/public.hpp:2,
                 from /home/jonathan/Downloads/hyprlang-0.6.1/src/common.cpp:1:
/home/jonathan/Downloads/hyprlang-0.6.1/src/../include/hyprlang.hpp:11:10: fatal error: print: No such file or directory
   11 | #include <print>
      |          ^~~~~~~
compilation terminated.
In file included from /home/jonathan/Downloads/hyprlang-0.6.1/src/public.hpp:2,
                 from /home/jonathan/Downloads/hyprlang-0.6.1/src/config.hpp:1,
                 from /home/jonathan/Downloads/hyprlang-0.6.1/src/config.cpp:1:
/home/jonathan/Downloads/hyprlang-0.6.1/src/../include/hyprlang.hpp:11:10: fatal error: print: No such file or directory
   11 | #include <print>
      |          ^~~~~~~
compilation terminated.
gmake[3]: *** [CMakeFiles/hyprlang.dir/build.make:79: CMakeFiles/hyprlang.dir/src/common.cpp.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[3]: *** [CMakeFiles/hyprlang.dir/build.make:93: CMakeFiles/hyprlang.dir/src/config.cpp.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:1018: CMakeFiles/hyprlang.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:1025: CMakeFiles/hyprlang.dir/rule] Error 2
gmake: *** [Makefile:544: hyprlang] Error 2

**Comment by j-koziel** [comment]
Seems to be an issue from v6 on wards as it builds on v0.5.3. I am using Ubuntu 24.04

**Comment by vaxerski** [comment]
outdated gcc
