### ISSUE TITLE
Empty path in `Cflags` in pkg-config file

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprlang#11]
Regressed by db5e1399b90d due to using `CMAKE_INSTALL_INCLUDEDIR` without `include(GNUInstallDirs)`. Also, without `_FULL` infix `CMAKE_INSTALL_INCLUDEDIR` expands to `-Iinclude` (relative path) which is still unusable via pkg-config.

```
$ cmake -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/hyprlang_prefix -B /tmp/hyprlang_build
$ cmake --build /tmp/hyprlang_build 
$ cmake --install /tmp/hyprlang_build
$ PKG_CONFIG_PATH=/tmp/hyprlang_prefix/share/pkgconfig pkg-config --cflags hyprlang
-I
$ fgrep includedir /tmp/hyprlang_prefix/share/pkgconfig/hyprlang.pc
includedir=
Cflags: -I${includedir}
```
breaking xdg-desktop-portal-hyprland v1.3.0 on FreeBSD:
```
/usr/bin/clang++ ... -I -I/usr/local/include/libdrm ...

In file included from ../src/portals/Screenshot.cpp:2:
In file included from ../src/portals/../core/PortalManager.hpp:14:
/usr/local/include/xf86drm.h:40:10: fatal error: 'drm.h' file not found
#include <drm.h>
         ^~~~~~~
```

**Comment by jbeich** [comment]
`CMAKE_INSTALL_INCLUDEDIR` isn't set by default without `include(GNUInstallDirs)`. Besides, `CMAKE_INSTALL_INCLUDEDIR` (instead of `CMAKE_INSTALL_FULL_INCLUDEDIR`) leads to `-Iinclude` which is invalid as it contains relative path.

**Comment by jbeich** [comment]
Err, relative path is invalid from the POV of system-wide installation.

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
@jbeich can you test with https://github.com/hyprwm/hyprlang/commit/4c28464a7d7af69b8da2fbbf4ec0b5ef4e960054?

**Comment by jbeich** [comment]
I confirm, works fine now.
